# Generated by Django 5.1.4 on 2026-09-22 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeclineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_cd', models.FloatField(verbose_name='走低门槛（坎德拉）')),
                ('updated_by', models.CharField(max_length=64, verbose_name='设定人')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('measured_cd', models.FloatField(verbose_name='实测光强')),
                ('required_cd', models.FloatField(verbose_name='要求光强')),
                ('bearing_error_deg', models.FloatField(verbose_name='方位偏差')),
                ('verdict', models.CharField(max_length=20, verbose_name='结论')),
                ('note', models.CharField(max_length=200, verbose_name='说明')),
                ('created_by', models.CharField(max_length=64, verbose_name='登记人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeclineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid_code', models.CharField(max_length=40, verbose_name='航标编号')),
                ('threshold_cd', models.FloatField(verbose_name='当时门槛（坎德拉）')),
                ('drop_cd', models.FloatField(verbose_name='走低差额（坎德拉）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curr_reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inspection.inspection', verbose_name='本笔')),
                ('prev_reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inspection.inspection', verbose_name='上一笔')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
